<?php include "header.phtml" ?>
<div align="center">
<h1>Survey completed! </h1>
Your survey has been completed successfully.<br><br>
<!--    Plz remember that your customer id is --><?//= $accountId ?><!-- <br><br>-->
<!--    You should use this id with your password to login your user account<br><br><br>-->
<a href=<?= $linkTo('accountIndex'); ?>>Back</a>
<br>
</div>

<?php include "footer.phtml" ?>

